# Generated by Django 2.1 on 2020-02-21 12:46

from django.db import migrations, models
import django.utils.timezone
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
